### ISSUE TITLE
android - testbed_simple compilation fails when running with proguard

### ISSUE THREAD

**Issue by guysegal** [BranchMetrics/react-native-branch-deep-linking#194] opened 2017-04-29 10:08 UTC
my app didn't compile when running with proguard when I tried to create a relase apk, so I tried to do the same with testbed_simple app, and I noticed it doesn't compile as well.

When I added these lines to proguard-rules file the compilation was successfull:

`-keep class io.branch.** { *; }`
`-dontwarn io.branch.**`

I'm not sure this is ideal but I didn't manage to make it work in any other way..

also notice that this line also needed to be added to the proguard file (see: https://github.com/facebook/react-native/issues/11891)
`
-dontwarn android.text.StaticLayout
`
(it will be added permanently to react-native in 0.44)

**Comment by jdee** [comment] 2017-05-08 18:32
@guysegal Thanks for reporting this. I'll look into it and see about getting this into the next release as well.

**Comment by jdee** [comment] 2017-05-09 17:52
Hi @guysegal. I'm not sure how to produce this problem. In testbed_simple, I select the `release` Build Variant for both `app` and `react-native-branch` and then both Build > Build APK and Build > Generate Signed APK... succeed. Did you have to modify something to resemble your app setup?

**Comment by guysegal** [comment] 2017-05-09 17:55
Try this from the command line run: `gradlew assembleRelease`

**Comment by jdee** [comment] 2017-05-09 18:04
That seems to work too. It failed at first with an issue in the :app:bundleReleaseJsAndAssets task because the example apps install the SDK from `file:../..` instead of NPM, so the entire repo is copied under node_modules, and it didn't like something it found in the example apps. When I change the package.json to use:

```json
  "react-native-branch": "2.0.0-beta.3"
```

The gradle task succeeds. I haven't run into any proguard-related issues.

**Comment by guysegal** [comment] 2017-05-09 18:27
Ok, I'll try to reproduce later, I guess you can close thr issue

**Comment by jdee** [comment] 2017-05-09 18:46
In the event someone is building from a git branch, e.g. `git+https://github.com/BranchMetrics/react-native-branch-deep-linking#maintenance-1.1`, they won't be able to do a release build without some tweaks. I added this in the app/build.gradle:

```gradle
project.ext.react = [
    inputExcludes = [
        "android/**", 
        "ios/**",
        "node_modules/react-native-branch/examples/**",
        "node_modules/react-native-branch/native-tests/**"
    ]
]
```

That fixed the issue when using gradlew assembleRelease. I'm not sure if the react-native-branch package can add to this setting. It may be necessary to set it in the app.

I'll close this issue. Please reopen it if you still think the problem is ours and can provide some more information on how to produce it.

**Closed** 2017-05-09 18:47 UTC
