### ISSUE TITLE
Android: subscribe is re-happening when app is in background

### ISSUE THREAD

**Issue by avishayil** [BranchMetrics/react-native-branch-deep-linking#47] opened 2016-09-23 07:41 UTC
Case:
1. User enters the app from branch deep-link (for example, facebook web link).
2. User goes to another app (For example, WhatsApp) via the task manager.
3. User goes back to the app via the task manager - the subscribe method is triggering again.

**Comment by rt2zz** [comment] 2016-09-23 15:42
What version of react-native-branch do you have installed? Make you you are on the latest (0.7.x)

There was a bug in earlier versions that when the JS process restarted but the java process did not, the cached branch session would be re-emitted.

**Comment by avishayil** [comment] 2016-09-23 16:16
I'm on the latest version.

**Comment by sarriaroman** [comment] 2016-09-27 18:04
Same here, even killing the app and opening the app again suscribe is being triggered.

**Comment by rt2zz** [comment] 2016-10-04 10:15
@sarriaroman @avishayil I am not able to reproduce the duplicate subscribe calls you are describing. So here is my plan of attack:
- simplify the subscribe / initSession handling on the js side
- add a debug parameter to the RNBranch class that will help with log what is going on under the hood

**Comment by avishayil** [comment] 2016-10-23 09:58
Hi @rt2zz any news about this? still suffering from this...

**Comment by avishayil** [comment] 2016-10-31 09:52
Some useful logs:
1. Starting the app.
2. Going to deeplink
3. Task manager: going to another app, going back to app

````
10-31 11:49:08.061 16890-16890/com.zuznow.geektime D/RNBranch: onInitFinished
10-31 11:49:47.776 16890-16890/com.zuznow.geektime D/RNBranch: onInitFinished
10-31 11:49:47.787 16890-16890/com.zuznow.geektime D/RNBranch: sendRNEvent
10-31 11:49:47.788 16890-16890/com.zuznow.geektime D/RNBranch: Catalyst instance poller try 1
10-31 11:49:47.788 16890-16890/com.zuznow.geektime D/RNBranch: Catalyst instance active
10-31 11:49:57.235 16890-16890/com.zuznow.geektime D/RNBranch: onInitFinished
10-31 11:49:57.262 16890-16890/com.zuznow.geektime D/RNBranch: sendRNEvent
10-31 11:49:57.277 16890-16890/com.zuznow.geektime D/RNBranch: Catalyst instance poller try 1
10-31 11:49:57.277 16890-16890/com.zuznow.geektime D/RNBranch: Catalyst instance active
```

Seems that the onInitFinished & sendRNEvent are triggering every time.

**Comment by avishayil** [comment] 2016-10-31 11:35
Another update: I changed the implementation a little bit, removed onStart & changed onNewIntent:
````
    @Override
    public void onNewIntent(Intent intent) {
        RNBranchModule.initSession(intent.getData(), this);
    }
````

Now the problem is not happening, but when the app is killed linking not working.

**Comment by avishayil** [comment] 2016-10-31 11:40
Solved it (kinda workaround):
````
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        RNBranchModule.initSession(this.getIntent().getData(), this);
        super.onCreate(savedInstanceState);
    }
    @Override
    public void onNewIntent(Intent intent) {
        RNBranchModule.initSession(intent.getData(), this);
    }
````

**Comment by rt2zz** [comment] 2016-11-07 07:03
@avishayil great! I apologize for not being more responsive, just getting back into the swing of things now. Can you clarify how the above snippet solved the issue? I would like to look into it more this week and hopefully arrive at a working out of the box solution for everyone.

**Comment by avishayil** [comment] 2016-11-07 07:18
Hi, I don't have a deep knowledge on how this module works, I just saw the logs, used common sense, some trials, and it worked. It's probably not the correct way to do it, but it's working and it's on production right now.

**Comment by aaustin** [comment] 2016-11-23 17:39
Hey team - this is actually expected behavior.

On the native Android and iOS libraries, any time the app comes into foreground, we'll call the deep link handler callback. This is needed as it's a common use case where your app could be backgrounded, the user could click a link that takes them to the Play Store where they click open, then deep link data should be passed through. You'll need to add handling on your side to ensure this doesn't muck with your UX.

**Comment by aaustin** [comment] 2016-11-23 17:40
Any work around you found won't be supported by us unfortunately so if the library changes in the future, and this breaks, we can't help. Sorry!

**Closed by aaustin** 2016-11-23 17:40 UTC
