### ISSUE TITLE
Android `+match_guaranteed` always false

### ISSUE THREAD

**Issue by lewnelson** [BranchMetrics/react-native-branch-deep-linking#386] opened 2018-10-16 11:16 UTC
After following the documentation here [https://docs.branch.io/pages/apps/react-native/](https://docs.branch.io/pages/apps/react-native/) as well as here [https://docs.branch.io/pages/resources/matching/#configuring-your-android-app-for-100-match](https://docs.branch.io/pages/resources/matching/#configuring-your-android-app-for-100-match) and trying to use app links as well as not using app links, I cannot get `+match_guaranteed` to be true on Android.

I've tried to follow links directly from chrome as well as messages, hangouts etc. but they always come back as false for match guaranteed. Is there something I may have missed that isn't in the documentation above?

**Comment by sequoiaat** [comment] 2018-10-22 14:37
@lewnelson  We have tried to reproduce the issue but got the expected behavior. Can you please share some more information on your setup and versions so we can try to see if we are seeing a similar issue

**Comment by csalmi-branch** [comment] 2019-01-29 00:21
@lewnelson Are you still experiencing this issue?

**Comment by csalmi-branch** [comment] 2019-02-13 03:01
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed by csalmi-branch** 2019-02-13 03:01 UTC
