### ISSUE TITLE
[iOS] Use of undeclared identifier 'app'

### ISSUE THREAD

**Issue by ssomnoremac** [BranchMetrics/react-native-branch-deep-linking#262] opened 2017-09-10 00:20 UTC
Following the link instructions for iOS on RN48 I'm getting this 

Use of undeclared identifier 'app'      right here V
```
  if (![RNBranch.branch application:app openURL:url options:options]) {
```

**Comment by jdee** [comment] 2017-09-11 16:29
There are two methods on the Branch singleton that mirror methods in the UIApplicationDelegate protocol. You should use whichever one suits your use case, and pass the arguments to the method directly, whatever you happen to call them in your app:

```Obj-C
- (BOOL)application:(UIApplication *)firstArg openURL:(NSURL *)secondArg options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)thirdArg
{
  return [RNBranch.branch application:firstArg openURL:secondArg options:thirdArg];
}
```

```Obj-C
- (BOOL)application:(UIApplication *)firstArg openURL:(NSURL *)secondArg sourceApplication:(NSString *)thirdArg annotation:(id)fourthArg {
  return [RNBranch.branch application:firstArg openURL:secondArg sourceApplication:thirdArg annotation:fourthArg];
}
```

You can also see the various examples in the repo.

**Comment by ssomnoremac** [comment] 2017-09-13 22:49
or perhaps I just didn't finish the setup?

> iOS Project Setup

Might I suggest you group the setup procedures by platform. A lot of people could be doing one and not the other, or just at different times. This ordering was confusing to me
```
Installation
Setup
  iOS Project
    objC
    swift
  Android Project
  iOS Project Setup  
  Android Project Setup
```
could the iOS parts be together? Its redundant to have a setup within the header "Setup". Maybe just objC, swift, and then "shared"?

**Comment by jdee** [comment] 2017-09-14 17:53
Thanks for the feedback. The [official docs](https://docs.branch.io/pages/apps/react-native/) are a little easier to follow. Both could use some editorial and formatting work. There is also now a tutorial app that leads you through adding Branch to an example app step by step. (See #270.) The README was completely rewritten recently, taking bits from different places and adding new content. It can definitely use some work. Part of the issue is that there are a number of different ways to integrate React Native, particularly on iOS, that it's hard to just have a section with iOS instructions and keep it readable. At any rate, you should probably get all of the Xcode steps in one place and the Android Studio steps in one place for convenience. This will get another round of edits soon.

**Comment by sequoiaat** [comment] 2018-05-14 13:01
@ssomnoremac Hope things are clarified well now. Can we close this issue?  Please let us know if you have more questions.

**Closed** 2018-06-15 13:10 UTC
