### ISSUE TITLE
showShareSheet does not generate short link on iOS 11.2.2

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#319] opened 2018-01-30 01:57 UTC
System version: iOS 11.2.2 (real device)

When I call:
```es6
const shareOptions = {
  messageHeader: "header",
  messageBody: "Register on IvySpace with this link and get 100$",
  emailSubject: "subject"
};
const linkProperties = {
  alias: "test-stage-ivy-559"
};

buo.showShareSheet(shareOptions, linkProperties);
```
Share window opens, I press copy, I paste it in inbox and I get very ugly, long link instead of short one:

> Register on IvySpace with this link and get 100$
> https://ivyspace.test-app.link/?%24identity_id=486697102521515013?alias=test-stage-ivy-559&channel=Pasteboard&feature=share&type=0&duration=0&source=ios&data=eyIkY2Fub25pY2FsX2lkZW50aWZpZXIiOiI1NTktc3RhZ2UiLCIkZW1haWxfc3ViamVjdCI6Ikl2eVNwYWNlOiAifQ%3D%3D
> 

On android it works as expected. Also on iOS 11.2 (simulator) it works without any issues.

**Comment by sequoiaat** [comment] 2018-05-09 16:16
@eahenke  We tried it on versions - iOS 11.3 but could not reproduce the issue . Short urls were getting generated in both cases. Is this still an open  issue for you ?

**Comment by Hitabis** [comment] 2018-05-18 13:32
@sequoiaat This happens to us when we disable tracking. is that intended?

**Comment by eahenke** [comment] 2018-05-18 16:47
@sequoiaat Yes, still an issue, but it's only happening on 1 device - was on 11.2.5, but has since upgraded to 11.3.1.  All other devices are generating links correctly, but this one device generates links like: 

https://bnc.lt/a/key_live_[OUR_LIVE_KEY]?channel=Slack&feature=referral&type=0&duration=0&source=ios&data=eyJyZWZlcnJlcl9sYXN0TmFtZSI6IkRlbm5pcyIsIiRvZ19kZXNjcmlwdGlvbiI6Ikl0J3MgYSBuZXcgY29tbXVuaXR5IGNvbm5lY3RpbmcgcGVvcGxlIHdpdGggaGVhbHRoeSBsaWZlc3R5bGUgYnJhbmRzIiwicmVmZXJyZXJfaW1hZ2VfdXJsIjoiaHR0cHM6Ly9sb29rYXNpZGUuZmFjZWJvb2suY29tL3BsYXRmb3JtL3Byb2ZpbGVwaWMvP2FzaWQ9MTAxNTQ5NjMwMDYxMTYyMTEmaGVpZ2h0PTIwMCZ3aWR0aD0yMDAmZXh0PTE1MjU1NDU2OTImaGFzaD1BZVNEeXVMM2k4VkF4ZWFDIiwicmVmZXJyZXJfZmlyc3ROYW1lIjoiRGF2ZSIsIiRlbWFpbF9zdWJqZWN0IjoiSGV5LCBjaGVjayBvdXQgdGhlIG15VXBzaWRlIGFwcCEiLCJyZWZlcnJhbF9jb2RlIjoiUzJENjhXTUR6IiwiJG9nX3RpdGxlIjoiSGV5LCBjaGVjayBvdXQgdGhlIG15VXBzaWRlIGFwcCEiLCIkY2Fub25pY2FsX2lkZW50aWZpZXIiOiJSZWZlcnJhbC1TMkQ2OFdNRHoifQ%3D%3D

Since I can only reproduce on a single user's device, is it possible there is some phone setting that is causing this?

Thanks.

**Comment by Sarkar** [comment] 2018-06-08 00:16
@eahenke it's very possible. Those long links are only created in the case of low/weak network connectivity. If there is a timeout, then the default will be these long links. @Hitabis, yes, that is intended.

I'll close this for now, but please re-open if you feel like this isn't sufficient enough.

**Closed by Sarkar** 2018-06-08 00:16 UTC
