### ISSUE TITLE
Unexpected behavior in case of re-subscription

### ISSUE THREAD

**Issue by kyo504** [BranchMetrics/react-native-branch-deep-linking#73] opened 2017-01-13 03:17 UTC
I want to subscribe incoming links only if user logs in so  I call subscribe method when user logs in and call unsubscribe method when user logs out. However I've seen some kind of unexpected behavior. Here is the my test environment and simplified repro steps.

### Test environment
- Platform : iOS, Android
- RN version : 0.37
- Branch version : 0.9.0

### Steps to reproduce
1. Launch app ( with branch.subscribe(...) )
2. Go to background and open app again via branch deep link ( This triggers some actions in app )
3. Call unsubscribe
4. Re-subscribe

### Expected behavior
App should not do anything.

### Actual behavior
Subscription callback is triggered and the app does the same actions.

I thought that callback shouldn't be called because I've already consumed previous incoming link but it is called again. Is this expected behavior or a bug?

**Comment by jdee** [comment] 2017-01-13 18:48
@kyo504 This sounds like a bug, but I'll investigate.

**Comment by jdee** [comment] 2017-01-16 22:47
@kyo504 I can reproduce this problem. It's definitely not correct behavior. There is a branch called `resubscription-fix` in this repo with a small fix that should help, though there are some other things to consider before a final fix.

But I wonder about the use case you describe. I'm not sure why you're calling unsubscribe. Clearly then the app will do nothing, which I'm sure is what you want. Maybe the user just gets a login screen while they are not logged in and can do nothing else. But links are opened by the operating system regardless of app state. It's up to the app what if anything to do when a link is opened, but the point of calling subscribe is just to be notified when the operating system has opened a link in the app. For example, maybe you could allow the user to login and then be taken the link they opened, rather than having to go back and open the link again (just as users are taken to a link after an initial install). Or later you might add content like a promotion that users should see even if they are not logged in. And if you are logging custom analytics events when links are opened, you'd probably want to log them even when the user is not authenticated.

I'm new to this project, but I've worked a lot with the native Branch iOS SDK. The native SDKs work differently. Though it is part of the react-native-branch SDK, I think that calling unsubscribe when the user logs out amounts to an unintended use that will probably produce problems (like this one). I would recommend that you just never unsubscribe after calling subscribe, except perhaps at app termination, but rather just ignore links if the user is not logged in. For example:

```js
branch.subscribe((bundle) => {
  if (!User.loggedIn) return;

  // Now handle the link
}
```

**Comment by kyo504** [comment] 2017-01-17 05:52
@jdee Thanks for your investigation!

It will take some time to test the repo with RN 0.40 because our app is quite big and we are planning to upgrade RN version at the end of this month. I'll try your fix when I'm ready.

I also wanted to subscribe once and handle incoming link according to login status like your suggestion. However it wasn't easy to achieve the expected result because other things(routing, redux) are related.

**Comment by jdee** [comment] 2017-01-17 19:35
@kyo504 Thanks for the info. I hope we can get a 0.9.1 release out in the next week or so or at least get you a fix to preview in a branch. If that is not fast enough for your needs, please let me know, and maybe we can get you something sooner. Thanks.

**Comment by jdee** [comment] 2017-01-20 22:56
Hi @kyo504. I may have fixed this issue. There is a branch here called `release-0.9.1` with those changes. The cached link now has a TTL, so it will only be returned during the first few seconds after launch. This works in testing. 0.9.1 will be released some time next week, but if you have a chance to try these changes, please let us know if they help. Thanks.

**Comment by jdee** [comment] 2017-01-31 20:32
Version 0.9.1 has been released with a fix for this bug.

**Closed by jdee** 2017-01-31 20:32 UTC
