### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by timursadykhov** [BranchMetrics/react-native-branch-deep-linking#84] opened 2017-01-23 20:47 UTC
Hello,

I'm trying to customize the actual link that is created by branch when I show the share sheet. Currently it's just a short url like `http://go.example.com/Abcd/[branch_uuid]` but what i'd like it to be is `http://go.example.com/event/[my_id]`. 

I tried to accomplish this by making linkProperties: 
`let linkProperties = { alias: 'http://go.example.com/event/test' };` 
and 
`let linkProperties = { alias: 'go.example.com/event/test' };` 
but neither seemed to do anything. 

How would I go about doing this?

I'm on **version 0.9.0** and I haven't seen anything that would suggest the feature was not available in this version.

Thank you,
Timur

**Comment by jdee** [comment] 2017-01-23 22:57
Hi @timursadykhov. It looks like this was an unintentional omission. For example, the word "alias" does not occur anywhere in the native RNBranch code for either platform. Also missing: campaign, stage, tags. I've already fixed this on the iOS side. I have a little more work to do on Android. We'll be doing a release 0.9.1 this week. There is currently a `release-0.9.1` branch in this repo. I should have the fix for your issue in that branch by the end of the day for you to try. I'll notify you when it's ready.

**Comment by timursadykhov** [comment] 2017-01-23 23:46
Ah I see. Thanks for the quick response, looking forward to the fix!

**Comment by jdee** [comment] 2017-01-24 00:52
@timursadykhov Those changes have been merged to `release-0.9.1`. I can generate a short URL with an alias. Please try it out when you have a chance. Thanks.

```js
import branch from 'react-native-branch'

buo = branch.createBranchUniversalObject("abc", { title: "A thing", contentDescription: "It is a thing."})
let linkProperties = { alias: "thing2", tags: [ "a_tag", "another_tag"] }
let controlParams = { "$desktop_url": "https://example.com", "$match_duration": 3600 }

buo.generateShortUrl(linkProperties, controlParams).then((response) => {
  console.log("Short URL: " + response.url)
})
```

**Comment by timursadykhov** [comment] 2017-01-24 06:32
Thanks for the quick turnaround @jdee!

Initially I was unable to build because line 110 in RNBranch.m `linkProperties.campaign = linkPropertiesMap[@"campaign"];` was throwing the error **Property 'campaign' not found on object of type 'BranchLinkProperties** 

I removed that line and was able to build fine. 

The changes work when passing alias to `generateShortUrl` however using it with `showShareSheet` results in a long link with a bunch of params. 

It ends up looking something like: `http://go.example.com/a/[branch_key]?identity_id=[...]?alias=go.example.com/alias_test&channel=sms&feature=share&type=0&duration=0&source=ios&data=[...]`

Am i wrong in assuming that the same short url should be automatically generated by `showShareSheet`?

**Comment by jdee** [comment] 2017-01-24 12:14
That probably means you're using an old version of the Branch SDK. Are you using Cocoapods for the SDK? You might consider doing a `pod update` to get the latest version of the SDK. I'm not sure that we can require a certain version of the native SDK with an NPM package, so we may have to be a little fancier about detecting what is or is not present. That might also explain why some of these things were originally missing.

If the SDK fails to communicate with the server, it cannot generate a short URL and instead falls back to a `/a` link like that so that you at least get something. I assume that's consistent for you though. I'll take a look and see if that happens for me. I wasn't testing with showShareSheet before.

**Comment by timursadykhov** [comment] 2017-01-24 16:57
I am using cocoapods, yeah. Running `pod update` actually resulted in what looks like a downgrade with a message of **Installing Branch 0.12.24 (was 0.12.4)**. I initially installed branch at version 0.9.0 only about a week ago so I would assume my SDK was/is up to date. Should I have the podfile target a specific version?

It seems showShareSheet is able to communicate with the server just fine because when I don't pass linkProperties it comes up with the same url as generateShortUrl. Only when receiving linkProperties does it return that `/a` link.

Let me know if I can provide any more info.

**Comment by jdee** [comment] 2017-01-24 17:30
That looks like an upgrade to me, since 24 > 4. 0.12.24 is the latest version of the Branch pod, which is what I'm using. (0.12.4 was released in July.) You should be able to uncomment your local changes that were needed to build.

As to why you had an older version, it's possible you had used CocoaPods before but not very recently. As of 1.0, `pod install` no longer calls `pod repo update` first. You can either do `pod install --repo-update` or `pod repo update; pod install` to make sure you get the latest on an install. (`pod update` does call `pod repo update` first by default.) So maybe when you ran `pod install` recently for Branch, you were hitting a very old instance of the CocoaPods repo. But I'm speculating.

Note there could also be a similar issue in Android with Gradle. I'm less familiar with the mechanics there, but Gradle might need to be explicitly told to use the latest version of the native dependency.

I can reproduce your issue. I'll get it fixed in 0.9.1. I'll probably have an update in the `release-0.9.1` branch later today. Thanks for your patience.

**Comment by timursadykhov** [comment] 2017-01-24 18:56
Cool, thanks for the explanation on cocoapods I think that's actually the case on my end. No idea why I thought it was a downgrade, have to agree 24 > 4 :)

I'll test on android later and let you know if I have any issues there.

**Comment by jdee** [comment] 2017-01-24 21:27
@timursadykhov Everything seems to be working for me in a test app on iOS without changes to the react-native-branch SDK. A couple of notes:

- Be sure to call `[RNBranch initSessionWithLaunchOptions:isReferrable:]` in your AppDelegate.m as discussed in Step 3 [here](https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/#ios-initialization). (You only add the first line. The second should already be there. The idea is to add it at the very beginning of `application:didFinishLaunchingWithOptions:`) For various reasons, the native SDK supports deferred initialization, and it may be initialized on the fly by a call to showShareSheet. Then there is a race. If the initialization response has not been received from the server by the time it needs to request the short link from the server, it generates a `/a` link. This was happening to me sporadically because I forgot to call the method above in a new test app.
- When you make multiple calls to showShareSheet or generateShortUrl with the same alias (from different instances of the app, e.g.), you'll get the same link back each time as long as the other parameters in the request are the same as when the link was first created. If the other parameters (besides alias) have changed since link creation, the new request will fail with a 409 Conflict status code.

I still need to verify the Android side, but it looks to me like showShareSheet should work fine with aliases and any other supported parameters on iOS.

**Closed** 2017-03-21 15:59 UTC
