### ISSUE TITLE
[Android] ERR_UNKNOWN_URL_SCHEME from facebook in app browser

### ISSUE THREAD

**Issue by good2hear** [BranchMetrics/react-native-branch-deep-linking#132] opened 2017-03-21 09:32 UTC
Hi there,

I'm having some issue with android facebook in app browser 

1. When first clicked on the link, it directs to our website and there is a button that directs to app on click -> getting net::ERR_UNKNOWN_URL_SCHEME 

2. It works fine with iOS facebook browser and any other android browers (using email, SMS, chrome, etc) android facebook in app browser seems like the only problem 

3. It used to work fine when I was using react-native < 0.40 and react-native-branch 0.9.1; in fact, back then it was only the facebook browser that opened the app and email, SMS directed to playstore instead (#64)

4. Didn't make any major change; currently using react-native 0.41.2 and react-native-branch 1.0.2 

5. I'm not using App Links (which supports from android 6.0) and test failed with android 4.4 and 7.0 

Is there anything I'm missing after the update?
Any comments will be appreciated!!

**Comment by good2hear** [comment] 2017-03-23 02:35
tested with react-native-branch 1.1.1 and got the same result.

**Comment by jdee** [comment] 2017-03-23 02:37
@good2hear Sorry for the delay. I'll look into this soon. I've been getting a new beta release together.

**Comment by kyo504** [comment] 2017-03-23 06:45
@jdee FYI, 

I had a couple of tests.
1. Even though I tested with old apk (RN:**0.37**, branch:**0.9.0**), this issue happened again.  So I guess this issue is not related to any version of branch package.
2. I had a doubt about Facebook app because this issue only happened in the FB app browser so I installed downgraded version(facebook-106-0-0-26-68). In this case, I could see error message like "Web page could not find" on header but app was redirected to app store.

I hope this would be helpful for further investigation.

**Comment by kyo504** [comment] 2017-03-23 08:50
Reason for fail to load page is...
```
market://details?id=com.feedyourmusic&resource=song&id=2524&_branch_match_id=373377108030788282&referrer=link_click_id%3D373377108030788282
```

**Comment by jdee** [comment] 2017-03-23 17:47
@good2hear @kyo504 I'd like to try to reproduce this problem. I have a few questions:

- Is this a released app, and does the problem occur with the version in Google Play? If so, then I can install it.
- Do you have a sample link that isn't working?
- Are you using the Branch live or test environment?
- Are you using Branch Deepviews? You said the link first directs to the web with a button to open the app. Or is it your page that has the button to open the app?
- Did you check "Always try to open the app" in the Branch Dashboard?
- Can you confirm what versions of Android have demonstrated this problem? You mentioned 4.4 and 7.0. Have you observed the issue on other versions?
- Regarding @kyo504's last comment: You say that's the reason the load fails. Is that the wrong URI scheme from a Branch redirect? That URI scheme should be the same as what is configured in the Branch Dashboard. Can you double-check that? Note that it can be different for the live and test environments.

**Comment by good2hear** [comment] 2017-03-24 01:56
@jdee Thanks for reply!! regarding your questions:

- It is a released app (FeedYourMusic) and the problem occurs with the version in Google Play, but then 
1. language is in Korean  
2. we fixed this issue temporarily by having our server redirect to google playstore instead of branch url

- You can use below sample link
   https://play.google.com/store/apps/details?id=com.feedyourmusic 
   tried it as a custom URL in Dashboard as google play search failed to load; it failed to load as well so we used this same url directly from our server (as mentioned above) now it goes to google playstore (whether app is installed or not) on tapping button from facebook browser

- using the Branch live. 

- not using Branch Deepviews; it's just a page in our website that has button to open the app

- Yeap.  "Always try to open the app" is checked in the Branch Dashboard 

- tested with 4.4.2, 5.0.1, 6.0.1 and 7.0

**Comment by kyo504** [comment] 2017-03-24 03:34
@jdee Here is a basic scenario for our deeplinking.
Step 1: User shares a track to FB
Step 2: If user clicks the shared link, FB in-app-browser opens our webpage which contains play store button.
Step 3: Then app is open if user clicks the button, 

Play Store button has a link like `https://feedyourmusic.app.link/?resource=song&id=2655` and when user clicks the button app is open via converted address like...

- market://details?id=com.feedyourmusic&resource=song&id=2524&_branch_match_id=373377108030788282&referrer=link_click_id%3D373377108030788282
- http://play.google.com/store/apps/details?id=com.feedyourmusic&resource=song&id=2524&_branch_match_id=373377108030788282&referrer=link_click_id%3D373377108030788282

According to (android doc)[https://developer.android.com/distribute/tools/promote/linking.html] FB in-app-**browser** may need to use the second(Right?) but it tries to open app using the first one.

Interest thing is if we follow the same sequences with FB website using chrome browser, it works as we expected.

**Comment by jdee** [comment] 2017-03-24 18:58
@kyo504 Thanks for the information. First, I set up a basic test to verify some things. I didn't see a problem like you report:

- Set up Branch test app in the Dashboard. Set "Always try to open the app" and disabled App Links, using only a custom URI scheme.
- Created a new link in the Marketing section of the Dashboard. Set the `$android_url` to point to a Google Play entry using an `https` URL.
- Shared the link on Facebook.
- On an Android 6.0 device, ensured the app associated with the custom URI scheme was not installed, to trigger a Play Store redirect.
- Viewed the share in Facebook app version 116.0.0.17.69. Tapped the link and was directed to a web view in Facebook. Eventually, it opened the Play Store app.
- Changed the `$android_url` to a `market://` link. Repeated the test. Again, it opened the Play Store app.

This all seemed correct to me. Here's my Branch link: https://l1mv.app.link/eKW81DyzMB. Perhaps you can confirm whether that link has the same problem when you test.

Here are my questions:

1. Can you please provide a sample Branch URL that has this problem? That would probably be the fastest way to see what's wrong.
1. When the user shares to FB from your RN app, do you use Branch? Which method do you use? showShareSheet, generateShortUrl?
1. Does the Play Store button on your website use a Branch link to direct to the app? How is that link generated?
1. What value are you setting for the `$android_url` control parameter (or the global Android redirect in the Dashboard, if you don't set `$android_url` in the BUO)? 

Sorry for all the questions. I think there's a time difference, so hopefully this will help resolve the problem.

**Comment by kyo504** [comment] 2017-03-27 08:31
@jdee Thanks for the investigation.
When I posted your link and clicked it in FB app, it brought me to play store but before switching application contexts error toast was shown. It said "Page cannot be loaded". Is it intended behavior? I thought it should have opened Dubar app because I had installed before click the link.

I have crated a simplified app which shows the same result. Here is the link(https://github.com/kyo504/BranchTest). If you clone and launch the app, you can see Share button. You press Share button to post content and click the link in FB app. Then you could see the same error in FB app browser.

Based on the application above, here are answers:
1. Maybe this link is what you want? `https://4240.app.link/t8eurZKFQB?resource=song&id=1046`
2. I just use RN `Share` component like below
```javascript
    Share.share({
      title: "Share with your friends",
      message: "http://www.feedyourmusic.com/share_test/1046"
    })
      .catch(error => console.log(error))
```
3. Play Store button has a link like https://4240.app.link/?resource=song&id=1046. Real application would have a link like https://feedyourmusic.app.link/?resource=song&id=1046. There is nothing special. Server just make string template with the give params(resource, id)
4. We don't use those parameters because we just use `Share` component, not BUO.

**Comment by jdee** [comment] 2017-03-27 18:02
Hi @kyo504. Thanks for the info. I can produce the problem, which is a step forward. One thing I noticed is that your Play Store button on the `/share_test/1046` page uses https://4240.app.link/?resource=song&id=1046 (no path), not https://4240.app.link/t8eurZKFQB?resource=song&id=1046. Is that intentional? It's possible to redirect to the root of the domain with parameters, but that won't be recognized as the same short link by Branch analytics. And it's possible this problem would go away if you used the second link. At any rate, there may be a bug redirecting from the domain root in this case. I don't think it has anything to do with RN or this repo.

I have some thoughts about how you might use Branch in the app. I'm going to submit a PR to the BranchTest app with some changes you might consider.

**Comment by jdee** [comment] 2017-03-27 20:34
@kyo504 I opened this [PR](https://github.com/kyo504/BranchTest/pull/1) with some suggestions.

**Comment by kyo504** [comment] 2017-03-28 02:06
Hi @jdee It's not intended to use the first link. How can I get the path? Is the path is generated by `generateShortUrl` method? And does it mean that I need to set `controlParams` and `linkProperties` in order to get the path? 

And thanks for your suggestion. I'll look through your pr, test, and ping you back. :)

**Comment by jdee** [comment] 2017-03-28 16:25
@kyo504 There are lots of means to create a link. Everything eventually uses the [Branch API](https://github.com/BranchMetrics/branch-deep-linking-public-api#creating-a-deep-linking-url). You can create links in the Marketing section of the Dashboard or using any SDK, including `react-native-branch`. A server can create short links using the API and then include them in the application API. It's up to you how and where to create them.

The path in the resulting URL is automatically generated by Branch unless you specify an `alias` key in the linkProperties. For example:

```js
let { url } = await branchUniversalObject.generateShortUrl({ 
  alias: 'install', 
  ... # other link properties
}, controlParams)
```

will result in https://4240.app.link/install or https://feedyourmusic.app.link/install. Aliases can only be used once. If you try to create a second `/install` link with different parameters, the underlying API call can fail. If you don't specify `alias`, the path is an arbitrary string generated by Branch, e.g. `t8eurZKFQB`.

There is some caching, both on the server and on the device, so if you call `generateShortUrl` more than once with the same parameters, you will get back the same link (with the same path) each time.

**Comment by jdee** [comment] 2017-03-29 00:56
@kyo504 I've added a realistic content-sharing sample app called `webview_example` in the `examples` subdirectory (formerly `testbed`). This illustrates link routing in addition to sharing. You can share links from the app, which then direct back into the app and display the correct content when opened.

**Comment by muvhaus-sl** [comment] 2017-04-06 14:04
Hi, I'm having very similar problem, but its happening on the Chrome browser.
A bit of background:
1. Links are being generated from the App (as a Share). They work fine on Desktop and iOS. Fail on Android.
2. I have gone thru the examples and made sure my Android manifest, activity and application had similar structure.
3. I copied all the Manifest additions straight from the walk-thru at Branch.io.
4. I verified the dashboard->link settings to match my expectations and needs. I added the Sha256, and correct scheme.

When I click on a link, I get the "Err_Unknown_Scheme", and on the details, it shows its trying to access "minfind://specimen/533106" (the number changes according to the content being shared), which is the URL that I parse on the app, and route to the proper view. This URL works fine on iOS.

I have tested the app by generating a releaseBuild and installing the APK to the device. And also tested in Debug. None of which seem to work.
My device is a brand new phone, with only the basics installed. Android 6.0.

Any ideas on how to overcome this issue?

**Comment by jdee** [comment] 2017-04-06 16:54
Hi @muvhaus-sl. Thanks for getting in touch.

This is almost certainly an issue with configuration, not an SDK issue, but just to be sure, what versions are you using of:

- react-native
- react-native-branch
- native Branch SDK (Android)

The easiest way to troubleshoot is to look at an example of a bad link that isn't redirecting properly. Ideally, it would be nice if I could reproduce the problem. Is your app published? Can I install it and try the same thing you're doing? Can you provide specific steps that produce the problem? Can you provide a bad URL that I can examine?

It doesn't really matter how a link is created. Your server can POST to the API, you can use any SDK (RN, native, web, etc.) or you can use the Marketing section of the Branch Dashboard. The Dashboard might be the easiest way for you to explore the problem, since it's easy to edit a link after it's created there. Then you can try different settings until it works, and then do the same thing with the SDK later.

Also, the Liveview & Export section of the Dashboard shows you data for all links, no matter how they're created. When your link redirects to the wrong URL/URI, it should show up near the top of the list in Liveview. Maybe examining the parameters there will help show what's wrong.

**Comment by muvhaus-sl** [comment] 2017-04-07 09:19
Hi @jdee,
I managed to get it to work, the only outstanding issues are:

- Facebook App (always take me to Playstore, and then to the App. I assume its because I did not installed the app from PlayStore, but used an APK?
- Non Chrome browsers.

Those are minor and confined... so I think I'm fine for now.

**Comment by kyo504** [comment] 2017-04-11 08:00
@jdee Thanks for your great support. With your suggestion, now it works fine in Android. You can close this issue. 👍

**Comment by jdee** [comment] 2017-04-11 17:04
@kyo504 I'm glad it worked for you. Do you have any further use for that PR? If not, I'll close it and delete that fork. But there's no problem leaving it if it's still useful to you.

**Comment by kyo504** [comment] 2017-04-12 01:50
I learned pretty much things from your PR. Now you can close it. Thanks :)

**Closed** 2017-04-13 06:05 UTC

**Comment by cears-bhumika** [comment] 2017-05-11 11:14
Hi @jdee,

I am generating link using Universal branch object in that i am passing "market://details" url in $android_url. it is always redirecting play store if application is installed then also its redirecting play store. But if i write "https://play.google.com" in $android_url then it is open the application if installed and if not installed then its redirecting play.google.com in mobile browser but i want to open playstore appliction.

Please help me .
Thanks

**Comment by youjust** [comment] 2021-05-22 20:11
Tnx support me
